const mongoose = require("mongoose");

const usersSchema = new mongoose.Schema({
    profileFor: String,
    name: String,
    bodyType: String,
    age: String,
    physicalStatus: String,
    height: String,
    weight: String,
    motherTongue: String,
    maritalStatus: String,
    eatingHabits: String,
    drinkingHabits: String,
    smokingHabits: String,
    religion: String,
    casteSubCaste: String,
    gothram: String,
    starRaasi: String,
    dosham: String,
    timeOfBirth: String,
    placeOfBirth: String,
    country: String,
    state: String,
    city: String,
    citizenship: String,
    ancestralOrigin: String,
    education: String,
    educationInDetail: String,
    collegeInstitution: String,
    additionalDegree: String,
    employedIn: String,
    occupation: String,
    familyValues: String,
    familyType: String,
    familyStatus: String,
    numberOfSisters: String,
    fatherOccupation: String,
    motherOccupation: String,
    numberOfBrothers: String,
    familyLocation: String,
    aboutMyFamily: String,
    hobbiesAndInterests: String,
})

module.exports = mongoose.model("users", usersSchema)